Ext.define('LearningJourney.store.UndergraduateStore',{
    extend:'Ext.data.Store',
    config:{
    model:'LearningJourney.model.UndergraduateModel',
    sorters:'courseName',
    grouper:{
        groupFn: function(record) {
        return record.get('courseName')[0];
       }
   },
   data:[
       {courseName: 'Accountancy'},
       {courseName: 'Anatomical Sciences'},
       {courseName: 'Animation'},
       {courseName: 'Applied Computing'},
       {courseName: 'Applied Computing: Games'},
       {courseName: 'Applied Computing: Human Computer Interaction'},
       {courseName: 'Architecture'},
       {courseName: 'Art & Design (General Foundation)'},
       {courseName: 'Art, Philosophy, Contemporary Practices'},
       {courseName: 'Arts General (full time)'},
       {courseName: 'Arts General (part time daytime)'},
       {courseName: 'Arts General (part time evening)'},
       {courseName: 'Biochemistry'},
       {courseName: 'Biological Chemistry and Drug Discovery'},
       {courseName: 'Biological Sciences'},
       {courseName: 'Biomedical Sciences'},
       {courseName: 'Business Computing'},
       {courseName: 'Business Economics with Marketing'},
       {courseName: 'Business Management'},
       {courseName: 'Childhood Practice'},
       {courseName: 'Civil Engineering'},
       {courseName: 'Community Learning and Development'},
       {courseName: 'Computing Science'},
       {courseName: 'Creative Writing'},
       {courseName: 'Dentistry'},
       {courseName: 'Digital Interaction Design'},
       {courseName: 'Drug Discovery'},
       {courseName: 'Early Childhood Studies(Childhood Practice)'},
       {courseName: 'Economic Studies'},
       {courseName: 'Education (Primary)'},
       {courseName: 'Electronic Engineering'},
       {courseName: 'English / English and Film Studios'},
       {courseName: 'Environmental Science'},
       {courseName: 'Environmental Science (with Dundee & Angus College)'},
       {courseName: 'Environmental Sustainability'},
       {courseName: 'European Philosophy'},
       {courseName: 'European Politics'},
       {courseName: 'European Studies'},
       {courseName: 'Evening part time MA'},
       {courseName: 'Finance'},
       {courseName: 'Financial Studies'},
       {courseName: 'Fine Art (Digital Media, Drawing and Painting, Printmaking, Sculpture)'},
       {courseName: 'Forensic Anthropology'},
       {courseName: 'Foundation Year in Life Sciences'},
       {courseName: 'French'},
       {courseName: 'General Foundation in Art & Design'},
       {courseName: 'Geography'},
       {courseName: 'Geopolitics'},
       {courseName: 'German'},
       {courseName: 'Graphic Design'},
       {courseName: 'History'},
       {courseName: 'Applied Computing: Human Computer Interaction'},
       {courseName: 'Illustration'},
       {courseName: 'Interior and Environmental Design'},
       {courseName: 'International Business'},
       {courseName: 'International Relations'},
       {courseName: 'Jewellery and Metal Design'},
       {courseName: 'Languages'},
       {courseName: 'Law (including Law with Languages)'},
       {courseName: 'Life Sciences (with Dundee & Angus College)'},
       {courseName: 'Life Sciences (Foundation Year)'},
       {courseName: 'Life Sciences (Foundation Year) with English Language'},
       {courseName: 'Management (CertHE - part-time evening'},
       {courseName: 'Mathematical Biology'},
       {courseName: 'Mathematics'},
       {courseName: 'Mechanical Engineering'},
       {courseName: 'Medicine'},
       {courseName: 'Microbiology'},
       {courseName: 'Molecular Biology'},
       {courseName: 'Molecular Genetics'},
       {courseName: 'Neuroscience'},
       {courseName: 'Nursing'},
       {courseName: 'Oral Health Sciences'},
       {courseName: 'Part-time CertHE Management (evening)'},
       {courseName: 'Part-time MA (daytime)'},
       {courseName: 'Part-time MA (evening)'},
       {courseName: 'Phramacology'},
       {courseName: 'Philosophy'},
       {courseName: 'Physics'},
       {courseName: 'Physiological Sciences'},
       {courseName: 'Politics'},
       {courseName: 'Primary Education'},
       {courseName: 'Product Design'},
       {courseName: 'Professional Development'},
       {courseName: 'Professional Development in Leadership and Management'},
       {courseName: 'Professional Development in Community Engagement'},
       {courseName: 'Professional Development in Volunteer Management'},
       {courseName: 'Psychology'},
       {courseName: 'Renewables'},
       {courseName: 'Scottish Historical Studies'},
       {courseName: 'Social Work'},
       {courseName: 'Spanish'},
       {courseName: 'Spatial Economics'},
       {courseName: 'Teaching Qualification Further Education - TQFE'},
       {courseName: 'Textile Design'},
       {courseName: 'Time Based Art & Digital Film'},
       {courseName: 'Town and Regional Planning'}
       
   ]
    }
});