Ext.define('LearningJourney.model.LifeModel',{
    extend:'Ext.data.Model',
    config:{
        fields:['lifeMenuTitle',
                'lifeMenuDesc',
                'lifeMenuID'
        ]
    }
});